---
vault_postgres_db: notes_db
vault_postgres_user: notes_user
vault_postgres_password: mystrongpassword
vault_ssl_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDCzCCAfOgAwIBAgIUeOB+pVGnjAUrkBAfXxjgL18IgFgwDQYJKoZIhvcNAQEL
  BQAwFTETMBEGA1UEAwwKbm90ZXMuZG9iczAeFw0yNTA3MDQwOTA1MThaFw0yNjA3
  MDQwOTA1MThaMBUxEzARBgNVBAMMCm5vdGVzLmRvYnMwggEiMA0GCSqGSIb3DQEB
  AQUAA4IBDwAwggEKAoIBAQCwYBXLEA+beNqTFHGSEVeww1XfYlopqwaqekojsLJj
  EsjCaXtk9r9QSVIdSKxOKUiK9Ijk+q82+jW70MfUtFwSR4M8KQTHxlLr+mbKPOcm
  B3Lgu+93gz4GsnViZLo5BznUnz673Qxkuq3+SKuhxOSOCjEXaaVinuKw/D7wBaxi
  UMbG8etSgQVwG1zDcjShzQflO6nsaO7vRY31aGsbNnrHsW2x5UKktEIbGU5F842q
  SaiJatIUQ4GeNq5VkpAT8QkiIvGLB0a5Uy5AZR3xfnBnegQUwk32hE/lcdjoJX5O
  iORDT7HmkI2KPySeYxWxld7mHqOfX9SioP4BoU/AiULNAgMBAAGjUzBRMB0GA1Ud
  DgQWBBSLcavozTNrh9oO3rdccAf2mzFVyzAfBgNVHSMEGDAWgBSLcavozTNrh9oO
  3rdccAf2mzFVyzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAq
  RJUJnbVN2VXTx6frEK6kKiZfLcnx7Y03/VNY2I5RglkTVB+1jivZHhQXrfo0QeOa
  3A8PsbpPsNUWyIsVbVxsd279I45ZPk59Lx8Jtuj/LFVrf01YOESL2NxQTGRkeTIi
  99+/0G1FN7XFQ56+c5qcNhbzIuehhXJr+BAFW5ERlia4Tt4Uej9FcYaUHyf3eBof
  EoWaYRKV6IkAMwDUWjygVW3UxNdmoZC8qiZaiNd2BdKYAPJp+Gh37g6buCApaMX8
  G8aV7NWkrRtUcp+GLpodVezsyD0NMuKlRnxQLJ8d5nM+vjr3QSaugORf1EPj5td4
  oOfLBCa4JVYYKe9WNHYa
  -----END CERTIFICATE-----
vault_ssl_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCwYBXLEA+beNqT
  FHGSEVeww1XfYlopqwaqekojsLJjEsjCaXtk9r9QSVIdSKxOKUiK9Ijk+q82+jW7
  0MfUtFwSR4M8KQTHxlLr+mbKPOcmB3Lgu+93gz4GsnViZLo5BznUnz673Qxkuq3+
  SKuhxOSOCjEXaaVinuKw/D7wBaxiUMbG8etSgQVwG1zDcjShzQflO6nsaO7vRY31
  aGsbNnrHsW2x5UKktEIbGU5F842qSaiJatIUQ4GeNq5VkpAT8QkiIvGLB0a5Uy5A
  ZR3xfnBnegQUwk32hE/lcdjoJX5OiORDT7HmkI2KPySeYxWxld7mHqOfX9SioP4B
  oU/AiULNAgMBAAECggEAJVu80f2taJ+BIJ04bxmISvMdCcth0KieqVZsxMGFD3In
  nvJLxjdzj3RwVa6SfJ3G9VPVeTbWDR2TaxxOb3HifKa0F/aSQiRyZPRteFHNHiN+
  xDZagySD61Q6g+RVA4ZRzAUM+yrXmLBn8VAANqwnQyTKgCyK8Og5mQZc6GczO8GJ
  Cq/jUBEueqhArV8EL4CZQZqjgb/0yi5XTScys/ywc5oezirAvDbhc6Gg/NljUfbq
  -----END PRIVATE KEY-----