services:
  python_app:
    build: ./python_app
    container_name: python_app
    expose:
      - "8001"
    networks:
      - app_network  # Добавлено!

  node_app:
    build: ./node_app
    container_name: node_app
    expose:
      - "8002"
    networks:
      - app_network  # Добавлено!

  go_app:
    build: ./go_app
    container_name: go_app
    expose:
      - "8003"
    networks:
      - app_network  # Добавлено!

  java_app:
    build: ./java_app
    container_name: java_app
    expose:
      - "8004"
    networks:
      - app_network  # Добавлено!

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "443:443"
    depends_on:
      - python_app
      - node_app
      - go_app
      - java_app
    networks:
      - app_network  # Добавлено!

networks:
  app_network:
    driver: bridge  # Явное создание сети