global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['flask:5001']
    metrics_path: '/metrics'

  - job_name: 'goapp'
    static_configs:
      - targets: ['goapp:5002']
    metrics_path: '/metrics'
  - job_name: go-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: go-app
          service: go-app
          __path__: /home/alina2/go-app-logs/app.log
